### DISCUSSION TITLE
Operator core update

### DISCUSSION THREAD

**Discussion by aslakknutsen** [maistra/istio-workspace#753] [Ideas]
## Console Integration

- [x]  Move Session.Status.Refs.Resources to Conditions
- [x] combine all RefStatus.'Status' into a signle Status #70
- [ ]  Support components update on CRD for UI 'ready' wheel  #875
    ```
    status:
     readiness:
        components:
          pending: []
          ready:
            - grafana
            - istio-discovery
            - istio-egress
            - istio-ingress
            - kiali
            - mesh-config
            - prometheus
            - telemetry-common
            - tracing
          unready: []
    ```

## Reporting

- [x]  add multi error to all mutators #797 
- [x]  Add a 'realtime' status update type callback
- [ ]  write state/failure to the Event API

## Target project Validation

- [x]  ( "DryRun" Conditions to show full expected state on first run through, for then to become 'true' over time) https://github.com/maistra/istio-workspace/issues/864

## Refactor/Debt

- [x] rework locators/mutators/revertors into a 'Rule/Condition' type structure
- [x]  combine mutators and revertors
- [x]  Single location for convertion between external/internal objects
- [ ]  ( Reconcile per Condition )
- [x]  move Session locator state to Context object
- [x] Don't rely on Status for state storage, tag objects with Labels/annotations (this was under the assumption that status was an open field anyone could edit, but it's a separate path and under rbac so less likely). An error cause could fail to update status but after the changes have occured leaving us with an unknown/leaky sate.

## Done

- [x] Add reason/cause message to status - https://github.com/maistra/istio-workspace/issues/766
- [x] Add timestamp to status - https://github.com/maistra/istio-workspace/issues/765
- [x]  support Kind as part of ref name to be specific between Deployment and DeploymentConfig #783
- [x]  add custom resource view for cli  #782
- [x]  separate between Action and Success on RefStatus (Modified Failed) #781
