### ISSUE TITLE
Locate all references to a host/virtual service to setup the new route

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#138]
Currently, we only support to manipulate the direct virtual service that is named as the "dc derived host".

As a first step, we should locate all virtual services that contain a reference to the "dc derived host".

E.g. a Gateway connected VirtualService that refer to our target dc "productpage"

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "*"
  gateways:
  - bookinfo-gateway
  http:
  - match:
    - uri:
        exact: /productpage
    - uri:
        exact: /login
    - uri:
        exact: /logout
    - uri:
        prefix: /api/v1/products
    route:
    - destination:
        host: productpage
        port:
          number: 9080
```
'match' need to be cloned and restricted with the given header set and
'destination' needs to be updated to point to the manipulated subset
