### ISSUE TITLE
Release automation as CI job

### ISSUE THREAD

**Issue by bartoszmajsak** [Maistra/istio-workspace#163]
##### What can be improved

Instead of running it from dev machine we can have it as part of CircleCI.

The job would react on the pushed tag.

##### Why

![image](https://user-images.githubusercontent.com/719616/59914000-abdd2180-9419-11e9-8f51-8fd09c24094b.png)

#### How

```yaml
workflows:
  version: 2
  build-n-release:
    jobs:
      - build:
          filters:  # required since `release` has tag filters AND requires `build`
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
```

* the build job runs for all branches and all tags.
* runs release job on a tag and tag only using dedicated `filter` - tags starting with `v`
* release job runs goreleaser logic
