### ISSUE TITLE
Allow global defined env variables

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#271]
##### What can be improved

Define configuration/env variables on an 'ike' level and not just per command to avoid repeating the same configuration.

##### Why

Since we now have multiple cli commands that rely on the same parameters it could be useful to allow to define them on a global scale and not just per command. E.g. Namespace, Deployment, Session

Instead of:

```
IKE_CREATE_NAMESPACE=x
IKE_CREATE_DEPLOYMENT=y
IKE_CREATE_SESSION=z
IKE_DELETE_NAMESPACE=x
IKE_DELETE_DEPLOYMENT=y
IKE_DELETE_SESSION=z
```

Something like:

```yaml
namespace: x
deployment: ratings-v1
develop:
  session: x
create:
  session: y
delete:
  session: y
 ```

```
IKE_NAMESPACE=x
IKE_DEPLOYMENT=ratings-v1
IKE_SESSION=test
IKE_CREATE_ROUTE=y
IKE_CREATE_IMAGE=y
```
