### ISSUE TITLE
Add goreleaser

### ISSUE THREAD

**Issue by bartoszmajsak** [Maistra/istio-workspace#42]
https://github.com/goreleaser/goreleaser

**Comment by bartoszmajsak** [comment]
With a switch to `circle-ci` we can have following job in place:

```yaml
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:  # required since `release` has tag filters AND requires `build`
            tags:
              only: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
```

* the build job runs for all branches and all tags.
* runs release job on a tag and tag only using dedicated `filter` - tags starting with `v`
* release job runs goreleaser logic
