### ISSUE TITLE
API for choosing clone strategy

### ISSUE THREAD

**Issue by aslakknutsen** [Maistra/istio-workspace#61]
* Teleprecence
* Pure deployment
* Squash?

```yaml
spec:
  refs:
    - name: x-deploy
      strategy: telepresence
      args:
        version: 100.2
    - name: y-deploy
      strategy: image
      args:
        image: x/org:latest
```
