### ISSUE TITLE
Support components update on CRD for UI 'ready' wheel

### ISSUE THREAD

**Issue by aslakknutsen** [maistra/istio-workspace#874]
##### What can be improved

Describe a graphical component to display a nice wheel over the status of the session

##### Why

User friendly look :)

```yaml
status:
 readiness:
    components:
      pending: []
      ready:
        - grafana
        - istio-discovery
        - istio-egress
        - istio-ingress
        - kiali
        - mesh-config
        - prometheus
        - telemetry-common
        - tracing
      unready: []
```
